<!DOCTYPE html>
<!--[if gte IE 9]>
<html class="ie" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie-8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 7]>
<html class="ie-7" <?php language_attributes(); ?>>
<![endif]-->
<head>
	<!-- <meta charset="utf-8" /> -->
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<?php if ( is_singular() && pings_open( get_queried_object() ) ) { ?>
		<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
	<?php }
	wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<div class="wrapper"><!-- used to keep footer at the bottom of the browser window -->
<!--	<div id="slider_wrapper">-->
		<?php reddish_slider_template(); ?>
<!--	</div>-->
	<div id="menu_wrapper">
		<div id="page_top" class="container">
			<?php reddish_display_bloginfo_name();
			/* display menu; if no menu is assigned to the location, function wp_page_menu is called. UL element created by this function has default class 'menu', so in order to use the same styles for menus generated by these functions, 'menu' value is assigned to 'container_class' */
			wp_nav_menu( array(
				'theme_location'  => 'primary',
				'container_class' => 'site-navigation main-navigation',
			) ); ?>
			<div class="clear"></div>
		</div><!-- .container-->
		<div class="clear"></div>
	</div>
	<?php if ( get_header_image() ) { ?>
	<div id="custom-header">
		<img src="<?php header_image(); ?>" alt="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" />
	</div>
	<?php } ?>
	<div class="hdblock">
		<?php if ( ! is_404() ) : ?>
		<div class="container">
			<?php reddish_breadcrumbs(); ?>
			<div class="search_form right ">
				<?php get_search_form(); ?>
			</div><!-- .search_form -->
			<div class="clear"></div>
		</div><!-- .container-->
		<?php endif; ?><!-- ( ! is_404() -->
	</div><!-- hdblock -->
	<div class="clear"></div>
	<div class="container"><!-- start tag of the main-content block; end tag is in footer -->
